COLOR_DARK_PETROL = '#166151'
# COLOR_MEDIUM_PETROL = '#5bcfb6'
COLOR_LIGHT_PETROL = '#37d2b0'

COLOR_DARK_VIOLET = '#3f3c73'
COLOR_MEDIUMDARK_VIOLET = '#8816a6'
COLOR_MEDIUMLIGHT_VIOLET = '#ac89ca' 
COLOR_LIGHT_VIOLET = '#8B87C0'

PETROL_1 = '#0f4043'
PETROL_2 = '#165d61'
PETROL_3 = '#1e8085'
PETROL_4 = '#26a0a6'
PALETTE_PETROL = [PETROL_1, PETROL_2, PETROL_3, PETROL_4]

VIOLET_1 = '#423f78'
VIOLET_2 = '#514d93'
VIOLET_3 = '#625fab'
VIOLET_4 = '#7b79b9'
PALETTE_VIOLET = [VIOLET_1, VIOLET_2, VIOLET_3, VIOLET_4]


# PALETTE_CONTRAST = [COLOR_DARK_PETROL, COLOR_MEDIUM_PETROL, COLOR_LIGHT_PETROL]
# PALETTE_CONTRAST_SIMPLE = [COLOR_DARK_PETROL, COLOR_LIGHT_PETROL]

# PALETTE_CONTRAST2 = [COLOR_DARK_VIOLET, COLOR_MEDIUM_VIOLET, COLOR_LIGHT_VIOLET]
# PALETTE_CONTRAST2_SIMPLE = [COLOR_DARK_VIOLET, COLOR_LIGHT_VIOLET]

# PALETTE_CONTRAST3 = [COLOR_DARK_BLUE, COLOR_MEDIUMDARK_BLUE, COLOR_MEDIUMLIGHT_BLUE, COLOR_LIGHT_BLUE]
# PALETTE_CONTRAST3_3 = [COLOR_DARK_BLUE, COLOR_MEDIUMLIGHT_BLUE, COLOR_LIGHT_BLUE]
# PALETTE_CONTRAST3_SIMPLE = [COLOR_DARK_BLUE, COLOR_LIGHT_BLUE]

COLOR_DARK_BLUE = '#18206F'
COLOR_MEDIUMDARK_BLUE = '#3661AB'
COLOR_MEDIUMLIGHT_BLUE = '#5CABFF'
COLOR_LIGHT_BLUE = '#0FDFFF'

COLOR_HEIDENELKE = '#9C004B'
COLOR_GLUTROT = '#DA3C43'
COLOR_MEDIUM_RED = '#EC6200'
COLOR_LIGHT_RED = '#ff8f31'


COLOR_OCKER_ANDI = '#ebb300'

COLOR_DARK_PINK = '#9E4770'
COLOR_MEDIUMDARK_PINK = '#CD548D'
COLOR_MEDIUMLIGHT_PINK = '#EC8DC6'
COLOR_LIGHT_PINK = '#FDB5E0'

# COLOR_MEDIUM_RED = '#ff6933'
# COLOR_LIGHT_RED = '#FF9233'

COLOR_DARK_GREEN = '#416224'
COLOR_MEDIUMDARK_GREEN = '#4FB800'
COLOR_MEDIUMLIGHT_GREEN = '#AEA700'
COLOR_LIGHT_GREEN = '#CDD30F'

COLOR_NONE = '#8E8E8D'


PALETTE_THREE = [COLOR_MEDIUMDARK_BLUE, COLOR_GLUTROT, COLOR_MEDIUMDARK_GREEN]

PALETTE_REDS = [COLOR_HEIDENELKE, COLOR_GLUTROT, COLOR_MEDIUM_RED, COLOR_LIGHT_RED]
PALETTE_REDS_SIMPLE = [COLOR_HEIDENELKE, COLOR_GLUTROT]

PALETTE_GREENS = [COLOR_DARK_GREEN, COLOR_MEDIUMDARK_GREEN, COLOR_MEDIUMLIGHT_GREEN, COLOR_LIGHT_GREEN]
PALETTE_GREENS_SIMPLE = [COLOR_DARK_GREEN, COLOR_LIGHT_GREEN]

PALETTE_BLUES = [COLOR_DARK_BLUE, COLOR_MEDIUMDARK_BLUE, COLOR_MEDIUMLIGHT_BLUE, COLOR_LIGHT_BLUE]
PALETTE_BLUES_SIMPLE = [COLOR_DARK_BLUE, COLOR_LIGHT_BLUE]

PALETTE_VIOLETS = [COLOR_DARK_VIOLET, COLOR_MEDIUMDARK_VIOLET, COLOR_MEDIUMLIGHT_VIOLET, COLOR_LIGHT_VIOLET]
PALETTE_VIOLETS_SIMPLE = [COLOR_DARK_VIOLET, COLOR_LIGHT_VIOLET]

PALETTE_PINKS = [COLOR_DARK_PINK, COLOR_MEDIUMDARK_PINK, COLOR_MEDIUMLIGHT_PINK, COLOR_LIGHT_PINK]
PALETTE_PINKS_SIMPLE = [COLOR_DARK_PINK, COLOR_LIGHT_PINK]

PALETTE_W_NREUTRAL_BLUE = [COLOR_NONE, COLOR_DARK_BLUE, COLOR_MEDIUMDARK_BLUE, COLOR_MEDIUMLIGHT_BLUE, COLOR_LIGHT_BLUE]
PALETTE_W_NREUTRAL_RED = [COLOR_NONE, COLOR_HEIDENELKE, COLOR_GLUTROT, COLOR_MEDIUM_RED, COLOR_LIGHT_RED]
PALETTE_W_NREUTRAL_GREEN = [COLOR_NONE, COLOR_DARK_GREEN, COLOR_MEDIUMDARK_GREEN, COLOR_MEDIUMLIGHT_GREEN, COLOR_LIGHT_GREEN]
PALETTE_W_NREUTRAL_VIOLET = [COLOR_NONE, COLOR_DARK_VIOLET, COLOR_MEDIUMDARK_VIOLET, COLOR_MEDIUMLIGHT_VIOLET, COLOR_LIGHT_VIOLET]


PALETTE_FULLSCREEN_MODES = [COLOR_LIGHT_RED, COLOR_LIGHT_GREEN, COLOR_LIGHT_BLUE, COLOR_LIGHT_VIOLET]
PALETTE_FULLSCREEN_OPTIONS = [COLOR_LIGHT_RED, COLOR_LIGHT_GREEN, COLOR_LIGHT_BLUE]